apiVersion: v1
kind: Service
metadata:
  name: bmi-client-service
spec:
  type: LoadBalancer
  ports:
  - port: 80            # External port
    targetPort: 80      # Port on the container
  selector:
    app: bmi-client      # This should match your deployment's label